# Generated by Django 6.0 on 2025-12-20 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENTERED', 'Entered'), ('EXITED', 'Exited')], default='PENDING', max_length=10)),
                ('entry_flag', models.CharField(choices=[('NORMAL_ENTRY', 'Normal Entry'), ('FORCED_ENTRY', 'Forced Entry'), ('DUPLICATE_ENTRY', 'Duplicate Entry')], default='NORMAL_ENTRY', max_length=30)),
                ('laptop', models.CharField(blank=True, max_length=150, null=True)),
                ('extra', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_logs', to='users.user')),
            ],
            options={
                'db_table': 'entry_logs',
            },
        ),
        migrations.CreateModel(
            name='ExitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exit_flag', models.CharField(choices=[('NORMAL_EXIT', 'Normal Exit'), ('FORCED_EXIT', 'Forced Exit'), ('DUPLICATE_EXIT', 'Duplicate Exit'), ('INVALID_TOKEN_EXIT', 'Invalid Token Exit')], default='NORMAL_EXIT', max_length=30)),
                ('laptop', models.CharField(blank=True, max_length=150, null=True)),
                ('extra', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('entry_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_id', to='entries.entrylog')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_logs', to='users.user')),
            ],
            options={
                'db_table': 'exit_logs',
            },
        ),
        migrations.AddIndex(
            model_name='entrylog',
            index=models.Index(fields=['roll', 'status'], name='entry_logs_roll_id_d07c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='entrylog',
            index=models.Index(fields=['created_at'], name='entry_logs_created_2443f2_idx'),
        ),
        migrations.AddIndex(
            model_name='exitlog',
            index=models.Index(fields=['roll', 'exit_flag'], name='exit_logs_roll_id_aae378_idx'),
        ),
        migrations.AddIndex(
            model_name='exitlog',
            index=models.Index(fields=['created_at'], name='exit_logs_created_91862c_idx'),
        ),
    ]
