# Generated by Django 6.0 on 2026-01-04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "gate_outbox_events",
            },
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["sent_at"], name="outbox_sent_at_idx"),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["next_retry_at"], name="outbox_next_retry_idx"),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["created_at"], name="outbox_created_at_idx"),
        ),
    ]


