# Generated by Django 6.0 on 2025-12-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('roll', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['roll'], name='users_roll_ba5404_idx')],
            },
        ),
    ]
