# Generated by Django 6.0 on 2026-01-04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedGateEvent",
            fields=[
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(blank=True, default="", max_length=32)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "processed_gate_events",
            },
        ),
        migrations.AddIndex(
            model_name="processedgateevent",
            index=models.Index(fields=["received_at"], name="pge_received_at_idx"),
        ),
    ]


