# Generated by Django 6.0 on 2026-01-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entrylog',
            name='entry_logs_roll_id_d07c5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='entrylog',
            name='entry_logs_created_2443f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='exitlog',
            name='exit_logs_roll_id_aae378_idx',
        ),
        migrations.RemoveIndex(
            model_name='exitlog',
            name='exit_logs_created_91862c_idx',
        ),
        migrations.RemoveField(
            model_name='exitlog',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='exitlog',
            name='roll',
        ),
        migrations.DeleteModel(
            name='EntryLog',
        ),
        migrations.DeleteModel(
            name='ExitLog',
        ),
    ]


