# Generated by Django 6.0 on 2026-01-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylog',
            name='entry_flag',
            field=models.CharField(blank=True, choices=[('NORMAL_ENTRY', 'Normal Entry'), ('FORCED_ENTRY', 'Forced Entry'), ('DUPLICATE_ENTRY', 'Duplicate Entry')], max_length=30, null=True),
        ),
    ]
