# Generated by Cursor on 2026-01-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0004_alter_entrylog_entry_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="exitlog",
            name="device_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="exitlog",
            index=models.Index(fields=["entry_id"], name="exit_logs_entry_id_idx"),
        ),
    ]



