# Generated by Django 6.0 on 2026-01-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_exitlog_device_meta_entry_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitlog',
            name='exit_flag',
            field=models.CharField(choices=[('NORMAL_EXIT', 'Normal Exit'), ('EMERGENCY_EXIT', 'Emergency Exit'), ('ORPHAN_EXIT', 'Orphan Exit'), ('AUTO_EXIT', 'Auto Exit'), ('DUPLICATE_EXIT', 'Duplicate Exit')], default='NORMAL_EXIT', max_length=30),
        ),
    ]
