# Generated by Django 6.0 on 2026-01-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_exitlog_exit_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrylog',
            name='device_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrylog',
            name='os',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entrylog',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitlog',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exitlog',
            name='os',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitlog',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
