# Generated by Django 6.0 on 2026-01-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_remove_entrylog_entry_logs_roll_id_d07c5e_idx_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_roll_ba5404_idx',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]


